# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


# on:何时触发该事件. 
on:
  # 在push或pull请求事件时触发工作流，但只针对主分支
  push:
    branches: [ main ]


# 工作流运行由一个或多个jobs组成，这些job可以按顺序或并行运行
jobs:
  # 此工作流包含一个名为“build-deploy”的job。
  build-deploy:
    # 改job运行于什么虚拟机上
    runs-on: Ubuntu-18.04

    # steps表示将作为job一部分执行的一系列任务
    steps:
      - uses: actions/checkout@v2 # 切换分支到master
        with: 
              fetch-depth: 0
       
      - name: Use Node.js 15.x  #使用nodejs 12.x版本
        uses: actions/setup-node@v1 
        with:
          node-version: '15.x'

      - name: install and build #安装以来并打包，执行的是项目我们定义的命令
        run: npm install && npm run build
        
      - name: deploy #部署
        uses: JamesIves/github-pages-deploy-action@4.1.1 #和上面一样，这里使用的是他人写好的插件库，作用是发布到其他仓库中或者其他分支上，想要具体了解可以在插件库中搜索
        with:
          repository-name: xiaoyu-666/xiaoyu-666.github.io #推送到该仓库中，地址格式为github名称/仓库名
          branch: gh-pages #分支名
          folder: docs/.vuepress/dist #要推送的内容（打包后的博客文件夹）       
  
  
  sync: #同步到gitee仓库
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:xiaoyu-666/xiaoyu-666.github.io.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:x_xy/xiaoyu-blog.git
